### ISSUE TITLE
Crash in F-Droid builds >=5.0

### ISSUE THREAD

**Issue by github-user-1** [opacapp/opacclient#457]
I just upgraded to version 5.0.2 via F-Droid earlier today (Fairphone 2). Since then the app doesn't start anymore and I constantly get the Android-notification that the app crashed...

**Comment by raphaelm** [comment]
Does the notification offer you to send in a crash report? If so, please do that!

**Comment by github-user-1** [comment]
Unfortunately, not - this is the notification I get:

![screenshot_2016-10-20-18-56-07](https://cloud.githubusercontent.com/assets/6796538/19569917/231825b6-96e7-11e6-9651-1b4d8107c6d0.png)

If I click on this notification, I get:

![screenshot_2016-10-20-18-56-47](https://cloud.githubusercontent.com/assets/6796538/19569944/49d903d2-96e7-11e6-90d8-0bfd5f1d18d9.png)

Same thing happens if I just try to close the notification (swiping left of right). Android seems to try to start the app but always fails to do so.

**Comment by uvok** [comment]
Even after uninstall and reinstall, thus deleting app data, app crashes on startup. 
I could get a logcat. It's either one of these. 

``` 10-20 19:55:16.669 E/ACRA    (20166): ACRA caught a RuntimeException for de.geeksfactory.opacclient
10-20 19:55:16.669 E/ACRA    (20166): java.lang.RuntimeException: Unable to create application de.geeksfactory.opacclient.OpacClient: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.joda.time.DateTime.toString()' on a null object reference
10-20 19:55:16.669 E/ACRA    (20166): 	at de.geeksfactory.opacclient.OpacClient.onCreate(OpacClient.java:386)```

```10-20 19:55:16.449 E/ACRA    (20143): de.geeksfactory.opacclient fatal error : Unable to create application de.geeksfactory.opacclient.OpacClient: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.joda.time.DateTime.toString()' on a null object reference
10-20 19:55:16.449 E/ACRA    (20143): java.lang.RuntimeException: Unable to create application de.geeksfactory.opacclient.OpacClient: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.joda.time.DateTime.toString()' on a null object reference
10-20 19:55:16.449 E/ACRA    (20143): 	at de.geeksfactory.opacclient.OpacClient.onCreate(OpacClient.java:386)```

**Comment by Buntbart** [comment]
exactly same behavior here including the notification.
Galaxy Nexus, Cyanogenmod 13, *.apk from F-Droid.

**Comment by johan12345** [comment]
I have already created a Merge Request in the fdroiddata repository that should fix this crash: https://gitlab.com/fdroid/fdroiddata/merge_requests/1771/

**Comment by github-user-1** [comment]
Just wanted to share that I upgraded to version 5.0.3 (via F-Droid) but unfortunately the app doesn't work at all still - it just crashes when started. So the issue persists.

**Comment by uvok** [comment]
5.0.3 from FDroid doesn't crash for me anymore. It starts with the configure wizard.

**Comment by johan12345** [comment]
The F-Droid build server for some reason does not download the library configuration files when building the app and the app is not prepared to update them if there are none included in the app. We will try to fix at least one of these problems this next week.

Until then, please use the Play Store version or the APK available at https://de.opacapp.net/apk/

@github-user-1 Are you sure that 5.0.3 from F-Droid is still crashing and not just showing an empty library list? If so, does the app allow you to send a crash report (and have you already done so)?

**Comment by github-user-1** [comment]
Here's the screenshot showing the version in F-Droid and the crash-screen I get - I also just sent in the crash-report via email (sorry I forgot to check if it's possible now - it wasn't previously but is feasible now):

![screenshot_2016-10-30-22-09-55](https://cloud.githubusercontent.com/assets/6796538/19840090/77ce4cc8-9ee6-11e6-9d51-eb58de79abdf.png)

![screenshot_2016-10-30-22-14-25](https://cloud.githubusercontent.com/assets/6796538/19840091/896512c8-9ee6-11e6-9624-95371d9e48f6.png)

**Comment by johan12345** [comment]
@github-user-1 Okay, thanks for the crash report. That crash would probably stop happening when you clear the app's data, but that won't help as it will show an empty library list then. So we'll look into that issue too.

**Comment by raphaelm** [comment]
**NOTE** The Play Store builds and the APK on our website work, but if you have a F-Droid installation, installing a different build of the app will require you to uninstall the F-Droid version first which will delete all data in the app.

**Comment by raphaelm** [comment]
# Update on F-Droid builds
We fixed an issue with our data server which was the primary reason for the 5.0.3 builds on F-Droid to not work.

## If you installed the app for the first time
Everything should be fine now. If not, please comment here.

## If you had the app installed in version 4.x before
You will need to re-create your library accounts in the app (i.e. re-enter your passwords). I'm truly sorry for this inconvenience. Once you re-created them, your starred items will still be there, they have not been deleted.

**Comment by johan12345** [comment]
Starting with the 5.0.4 release, the F-Droid build should now be equivalent to the Play Store version (i.e., it has the library configuration files included) again. So crashes related to this problem should now be resolved.
